package com.drink.mapper;

import com.drink.entity.Politicsstatus;

public interface PoliticsstatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbggenerated
     */
    int insert(Politicsstatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbggenerated
     */
    int insertSelective(Politicsstatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbggenerated
     */
    Politicsstatus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Politicsstatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table politicsstatus
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Politicsstatus record);
}