package com.drink.entity;

public class SysUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.rid
     *
     * @mbggenerated
     */
    private String rid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.uid
     *
     * @return the value of user_role.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.uid
     *
     * @param uid the value for user_role.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.rid
     *
     * @return the value of user_role.rid
     *
     * @mbggenerated
     */
    public String getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.rid
     *
     * @param rid the value for user_role.rid
     *
     * @mbggenerated
     */
    public void setRid(String rid) {
        this.rid = rid;
    }
}